### ISSUE TITLE
AWS CLI command not working with VPC outbound proxy

### ISSUE THREAD

**Issue by ashimamatiman83** [aws-samples/outbound-vpc-filtering-proxy#6]
Hi,
Once the setup was done I configured my client's environmental variable HTTP_PROXY and HTTPS_PROXY as in the output of the template.
Also I added  NO_PROXY=169.254.169.254 on the EC2. 
I tried running my AWS cli commands and they did not work.
I removed HTTPS_PROXY (only) and it worked.
I tried AWS cli with --no-verify-ssl and it failed again.
Is there a specific Version of AWS cli to be used with this solution? Am I missing something?

**Comment by tzvetkov75** [comment]
Hi @ashimamatiman83 , 
 169.254.169.254 provides only the EC2 meta data, aka credentials. The cli command is executes/communicates to AWS endpoints, see https://docs.aws.amazon.com/general/latest/gr/aws-service-information.html You will need to whitelist the endpoints in the proxy. Use aws --debug to see more information. Alternatively you can use VPC endpoints https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html
I hope this helps
